// pages/deptDetail/deptDetail.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
      //是否显示侧边导航标志
    isShowSideBar:false,
    activeName: '1',
    //侧边导航栏选择项
    activeKey: 0,
    allData:[
      {weekday:'周一',
       deptType:[
         {typeName:'内科系统',
         time1:[
            {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
            {deptName:'内分泌科',doctor:'任慧龙'},
            {deptName:'神经内科',doctor:'王武红'},
            {deptName:'血液化疗科',doctor:'徐涛'},
            {deptName:'血液化疗科',doctor:'张丕胜'},
            {deptName:'肾内科',doctor:'何永平'},
            {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
            {deptName:'消化科',doctor:'陆德文'},
            {deptName:'心血管内科',doctor:'李艳红'},
            {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
            {deptName:'呼吸与危重症医学科',doctor:'吕春儿'},
            {deptName:'内分泌科',doctor:'任慧龙'},
            {deptName:'神经内科',doctor:'黎良达'},
            {deptName:'血液化疗科',doctor:'徐涛'},
            {deptName:'血液化疗科',doctor:'张丕胜'},
            {deptName:'肾内科',doctor:'何永平'},
            {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
            {deptName:'消化科',doctor:'陆德文'},
            {deptName:'心血管内科',doctor:'李艳红'},
            {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
        },
         {  typeName:'外科系统',
            time1:[
              {deptName:'呼吸与危重症医学科',doctor:'王金波'},
              {deptName:'内分泌科',doctor:'陈明良'},
              {deptName:'神经内科',doctor:'王武红'},
              {deptName:'血液化疗科',doctor:'徐涛'},
              {deptName:'血液化疗科',doctor:'张丕胜'},
              {deptName:'肾内科',doctor:'何永平'},
              {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
              {deptName:'消化科',doctor:'陆德文'},
              {deptName:'心血管内科',doctor:'李艳红'},
              {deptName:'消化肝病内科',doctor:'李先鹏'}
          ],
          time2:[
              {deptName:'呼吸与危重症医学科',doctor:'冯机也'},
              {deptName:'内分泌科',doctor:'今元亨'},
              {deptName:'神经内科',doctor:'王武红'},
              {deptName:'血液化疗科',doctor:'徐涛'},
              {deptName:'血液化疗科',doctor:'张丕胜'},
              {deptName:'肾内科',doctor:'何永平'},
              {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
              {deptName:'消化科',doctor:'陆德文'},
              {deptName:'心血管内科',doctor:'李艳红'},
              {deptName:'消化肝病内科',doctor:'李先鹏'}
          ]
        },
         {typeName:'妇儿系统',
            time1:[
              {deptName:'呼吸与危重症医学科',doctor:'前后'},
              {deptName:'内分泌科',doctor:'地方士'},
              {deptName:'神经内科',doctor:'王武红'},
              {deptName:'血液化疗科',doctor:'徐涛'},
              {deptName:'血液化疗科',doctor:'张丕胜'},
              {deptName:'肾内科',doctor:'何永平'},
              {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
              {deptName:'消化科',doctor:'陆德文'},
              {deptName:'心血管内科',doctor:'李艳红'},
              {deptName:'消化肝病内科',doctor:'李先鹏'}
          ],
          time2:[
              {deptName:'呼吸与危重症医学科',doctor:'加分的'},
              {deptName:'内分泌科',doctor:'李开春'},
              {deptName:'神经内科',doctor:'王武红'},
              {deptName:'血液化疗科',doctor:'徐涛'},
              {deptName:'血液化疗科',doctor:'张丕胜'},
              {deptName:'肾内科',doctor:'何永平'},
              {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
              {deptName:'消化科',doctor:'陆德文'},
              {deptName:'心血管内科',doctor:'李艳红'},
              {deptName:'消化肝病内科',doctor:'李先鹏'}
          ]
        },
         {typeName:'眼耳鼻喉口',
            time1:[
              {deptName:'呼吸与危重症医学科',doctor:'陈东航'},
              {deptName:'内分泌科',doctor:'任慧龙'},
              {deptName:'神经内科',doctor:'王武红'},
              {deptName:'血液化疗科',doctor:'徐涛'},
              {deptName:'血液化疗科',doctor:'张丕胜'},
              {deptName:'肾内科',doctor:'何永平'},
              {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
              {deptName:'消化科',doctor:'陆德文'},
              {deptName:'心血管内科',doctor:'李艳红'},
              {deptName:'消化肝病内科',doctor:'李先鹏'}
          ],
          time2:[
              {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
              {deptName:'内分泌科',doctor:'任慧龙'},
              {deptName:'神经内科',doctor:'王武红'},
              {deptName:'血液化疗科',doctor:'徐涛'},
              {deptName:'血液化疗科',doctor:'张丕胜'},
              {deptName:'肾内科',doctor:'何永平'},
              {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
              {deptName:'消化科',doctor:'陆德文'},
              {deptName:'心血管内科',doctor:'李艳红'},
              {deptName:'消化肝病内科',doctor:'李先鹏'}
          ]
        },
         {typeName:'中医保健系统',
            time1:[
              {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
              {deptName:'内分泌科',doctor:'任慧龙'},
              {deptName:'神经内科',doctor:'王武红'},
              {deptName:'血液化疗科',doctor:'徐涛'},
              {deptName:'血液化疗科',doctor:'张丕胜'},
              {deptName:'肾内科',doctor:'何永平'},
              {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
              {deptName:'消化科',doctor:'陆德文'},
              {deptName:'心血管内科',doctor:'李艳红'},
              {deptName:'消化肝病内科',doctor:'李先鹏'}
          ],
            time2:[
                {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
                {deptName:'内分泌科',doctor:'任慧龙'},
                {deptName:'神经内科',doctor:'王武红'},
                {deptName:'血液化疗科',doctor:'徐涛'},
                {deptName:'血液化疗科',doctor:'张丕胜'},
                {deptName:'肾内科',doctor:'何永平'},
                {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
                {deptName:'消化科',doctor:'陆德文'},
                {deptName:'心血管内科',doctor:'李艳红'},
                {deptName:'消化肝病内科',doctor:'李先鹏'}
            ]
        },
         {typeName:'皮肤整容系统',
            time1:[
              {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
              {deptName:'内分泌科',doctor:'任慧龙'},
              {deptName:'神经内科',doctor:'王武红'},
              {deptName:'血液化疗科',doctor:'徐涛'},
              {deptName:'血液化疗科',doctor:'张丕胜'},
              {deptName:'肾内科',doctor:'何永平'},
              {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
              {deptName:'消化科',doctor:'陆德文'},
              {deptName:'心血管内科',doctor:'李艳红'},
              {deptName:'消化肝病内科',doctor:'李先鹏'}
          ],
          time2:[
              {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
              {deptName:'内分泌科',doctor:'任慧龙'},
              {deptName:'神经内科',doctor:'王武红'},
              {deptName:'血液化疗科',doctor:'徐涛'},
              {deptName:'血液化疗科',doctor:'张丕胜'},
              {deptName:'肾内科',doctor:'何永平'},
              {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
              {deptName:'消化科',doctor:'陆德文'},
              {deptName:'心血管内科',doctor:'李艳红'},
              {deptName:'消化肝病内科',doctor:'李先鹏'}
          ]
        }
       ]
      },
      {weekday:'周二',
      deptType:[
        {typeName:'内科系统',
        time1:[
           {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
           {deptName:'内分泌科',doctor:'任慧龙'},
           {deptName:'神经内科',doctor:'王武红'},
           {deptName:'血液化疗科',doctor:'徐涛'},
           {deptName:'血液化疗科',doctor:'张丕胜'},
           {deptName:'肾内科',doctor:'何永平'},
           {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
           {deptName:'消化科',doctor:'陆德文'},
           {deptName:'心血管内科',doctor:'李艳红'},
           {deptName:'消化肝病内科',doctor:'李先鹏'}
        ],
        time2:[
           {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
           {deptName:'内分泌科',doctor:'任慧龙'},
           {deptName:'神经内科',doctor:'王武红'},
           {deptName:'血液化疗科',doctor:'徐涛'},
           {deptName:'血液化疗科',doctor:'张丕胜'},
           {deptName:'肾内科',doctor:'何永平'},
           {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
           {deptName:'消化科',doctor:'陆德文'},
           {deptName:'心血管内科',doctor:'李艳红'},
           {deptName:'消化肝病内科',doctor:'李先鹏'}
        ]
       },
        {  typeName:'外科系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'妇儿系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'眼耳鼻喉口',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'中医保健系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
           time2:[
               {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
               {deptName:'内分泌科',doctor:'任慧龙'},
               {deptName:'神经内科',doctor:'王武红'},
               {deptName:'血液化疗科',doctor:'徐涛'},
               {deptName:'血液化疗科',doctor:'张丕胜'},
               {deptName:'肾内科',doctor:'何永平'},
               {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
               {deptName:'消化科',doctor:'陆德文'},
               {deptName:'心血管内科',doctor:'李艳红'},
               {deptName:'消化肝病内科',doctor:'李先鹏'}
           ]
       },
        {typeName:'皮肤整容系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       }, {typeName:'医技系统',
       time1:[
          {deptName:'X科',doctor:'徐涛'}
       ],
       time2:[
          {deptName:'呼吸与危重症医学科',doctor:'徐涛'}
       ]
      }
      ]
    },
      {weekday:'周三',
      deptType:[
        {typeName:'内科系统',
        time1:[
           {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
           {deptName:'内分泌科',doctor:'任慧龙'},
           {deptName:'神经内科',doctor:'王武红'},
           {deptName:'血液化疗科',doctor:'徐涛'},
           {deptName:'血液化疗科',doctor:'张丕胜'},
           {deptName:'肾内科',doctor:'何永平'},
           {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
           {deptName:'消化科',doctor:'陆德文'},
           {deptName:'心血管内科',doctor:'李艳红'},
           {deptName:'消化肝病内科',doctor:'李先鹏'}
        ],
        time2:[
           {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
           {deptName:'内分泌科',doctor:'任慧龙'},
           {deptName:'神经内科',doctor:'王武红'},
           {deptName:'血液化疗科',doctor:'徐涛'},
           {deptName:'血液化疗科',doctor:'张丕胜'},
           {deptName:'肾内科',doctor:'何永平'},
           {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
           {deptName:'消化科',doctor:'陆德文'},
           {deptName:'心血管内科',doctor:'李艳红'},
           {deptName:'消化肝病内科',doctor:'李先鹏'}
        ]
       },
        {typeName:'妇儿系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'眼耳鼻喉口',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'中医保健系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
           time2:[
               {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
               {deptName:'内分泌科',doctor:'任慧龙'},
               {deptName:'神经内科',doctor:'王武红'},
               {deptName:'血液化疗科',doctor:'徐涛'},
               {deptName:'血液化疗科',doctor:'张丕胜'},
               {deptName:'肾内科',doctor:'何永平'},
               {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
               {deptName:'消化科',doctor:'陆德文'},
               {deptName:'心血管内科',doctor:'李艳红'},
               {deptName:'消化肝病内科',doctor:'李先鹏'}
           ]
       },
        {typeName:'皮肤整容系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       }
      ]
    },
      {weekday:'周四',
      deptType:[
        {typeName:'内科系统',
        time1:[
           {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
           {deptName:'内分泌科',doctor:'任慧龙'},
           {deptName:'神经内科',doctor:'王武红'},
           {deptName:'血液化疗科',doctor:'徐涛'},
           {deptName:'血液化疗科',doctor:'张丕胜'},
           {deptName:'肾内科',doctor:'何永平'},
           {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
           {deptName:'消化科',doctor:'陆德文'},
           {deptName:'心血管内科',doctor:'李艳红'},
           {deptName:'消化肝病内科',doctor:'李先鹏'}
        ],
        time2:[
           {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
           {deptName:'内分泌科',doctor:'任慧龙'},
           {deptName:'神经内科',doctor:'王武红'},
           {deptName:'血液化疗科',doctor:'徐涛'},
           {deptName:'血液化疗科',doctor:'张丕胜'},
           {deptName:'肾内科',doctor:'何永平'},
           {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
           {deptName:'消化科',doctor:'陆德文'},
           {deptName:'心血管内科',doctor:'李艳红'},
           {deptName:'消化肝病内科',doctor:'李先鹏'}
        ]
       },
        {  typeName:'外科系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'妇儿系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'中医保健系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
           time2:[
               {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
               {deptName:'内分泌科',doctor:'任慧龙'},
               {deptName:'神经内科',doctor:'王武红'},
               {deptName:'血液化疗科',doctor:'徐涛'},
               {deptName:'血液化疗科',doctor:'张丕胜'},
               {deptName:'肾内科',doctor:'何永平'},
               {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
               {deptName:'消化科',doctor:'陆德文'},
               {deptName:'心血管内科',doctor:'李艳红'},
               {deptName:'消化肝病内科',doctor:'李先鹏'}
           ]
       },
        {typeName:'皮肤整容系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       }
      ]
    },
      {weekday:'周五',
      deptType:[
        {  typeName:'外科系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'妇儿系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'眼耳鼻喉口',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'中医保健系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
           time2:[
               {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
               {deptName:'内分泌科',doctor:'任慧龙'},
               {deptName:'神经内科',doctor:'王武红'},
               {deptName:'血液化疗科',doctor:'徐涛'},
               {deptName:'血液化疗科',doctor:'张丕胜'},
               {deptName:'肾内科',doctor:'何永平'},
               {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
               {deptName:'消化科',doctor:'陆德文'},
               {deptName:'心血管内科',doctor:'李艳红'},
               {deptName:'消化肝病内科',doctor:'李先鹏'}
           ]
       },
        {typeName:'皮肤整容系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       }
      ]
    },
      {weekday:'周六',
      deptType:[
        {typeName:'内科系统',
        time1:[
           {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
           {deptName:'内分泌科',doctor:'任慧龙'},
           {deptName:'神经内科',doctor:'王武红'},
           {deptName:'血液化疗科',doctor:'徐涛'},
           {deptName:'血液化疗科',doctor:'张丕胜'},
           {deptName:'肾内科',doctor:'何永平'},
           {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
           {deptName:'消化科',doctor:'陆德文'},
           {deptName:'心血管内科',doctor:'李艳红'},
           {deptName:'消化肝病内科',doctor:'李先鹏'}
        ],
        time2:[
           {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
           {deptName:'内分泌科',doctor:'任慧龙'},
           {deptName:'神经内科',doctor:'王武红'},
           {deptName:'血液化疗科',doctor:'徐涛'},
           {deptName:'血液化疗科',doctor:'张丕胜'},
           {deptName:'肾内科',doctor:'何永平'},
           {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
           {deptName:'消化科',doctor:'陆德文'},
           {deptName:'心血管内科',doctor:'李艳红'},
           {deptName:'消化肝病内科',doctor:'李先鹏'}
        ]
       },
        {  typeName:'外科系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'眼耳鼻喉口',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'中医保健系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
           time2:[
               {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
               {deptName:'内分泌科',doctor:'任慧龙'},
               {deptName:'神经内科',doctor:'王武红'},
               {deptName:'血液化疗科',doctor:'徐涛'},
               {deptName:'血液化疗科',doctor:'张丕胜'},
               {deptName:'肾内科',doctor:'何永平'},
               {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
               {deptName:'消化科',doctor:'陆德文'},
               {deptName:'心血管内科',doctor:'李艳红'},
               {deptName:'消化肝病内科',doctor:'李先鹏'}
           ]
       },
        {typeName:'皮肤整容系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       }
      ]
    },
      {weekday:'周日',
      deptType:[
        {typeName:'内科系统',
        time1:[
           {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
           {deptName:'内分泌科',doctor:'任慧龙'},
           {deptName:'神经内科',doctor:'王武红'},
           {deptName:'血液化疗科',doctor:'徐涛'},
           {deptName:'血液化疗科',doctor:'张丕胜'},
           {deptName:'肾内科',doctor:'何永平'},
           {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
           {deptName:'消化科',doctor:'陆德文'},
           {deptName:'心血管内科',doctor:'李艳红'},
           {deptName:'消化肝病内科',doctor:'李先鹏'}
        ],
        time2:[
           {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
           {deptName:'内分泌科',doctor:'任慧龙'},
           {deptName:'神经内科',doctor:'王武红'},
           {deptName:'血液化疗科',doctor:'徐涛'},
           {deptName:'血液化疗科',doctor:'张丕胜'},
           {deptName:'肾内科',doctor:'何永平'},
           {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
           {deptName:'消化科',doctor:'陆德文'},
           {deptName:'心血管内科',doctor:'李艳红'},
           {deptName:'消化肝病内科',doctor:'李先鹏'}
        ]
       },
        {  typeName:'外科系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'妇儿系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       },
        {typeName:'中医保健系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
           time2:[
               {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
               {deptName:'内分泌科',doctor:'任慧龙'},
               {deptName:'神经内科',doctor:'王武红'},
               {deptName:'血液化疗科',doctor:'徐涛'},
               {deptName:'血液化疗科',doctor:'张丕胜'},
               {deptName:'肾内科',doctor:'何永平'},
               {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
               {deptName:'消化科',doctor:'陆德文'},
               {deptName:'心血管内科',doctor:'李艳红'},
               {deptName:'消化肝病内科',doctor:'李先鹏'}
           ]
       },
        {typeName:'皮肤整容系统',
           time1:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ],
         time2:[
             {deptName:'呼吸与危重症医学科',doctor:'徐涛'},
             {deptName:'内分泌科',doctor:'任慧龙'},
             {deptName:'神经内科',doctor:'王武红'},
             {deptName:'血液化疗科',doctor:'徐涛'},
             {deptName:'血液化疗科',doctor:'张丕胜'},
             {deptName:'肾内科',doctor:'何永平'},
             {deptName:'肿瘤放化疗中心',doctor:'程晓春'},
             {deptName:'消化科',doctor:'陆德文'},
             {deptName:'心血管内科',doctor:'李艳红'},
             {deptName:'消化肝病内科',doctor:'李先鹏'}
         ]
       }
      ]
    }
    ],
    leftMenu:[],
    //右侧内容数组
    rightContent:[]
  },
  //点击显示侧边导航栏
  triggerSidebar(){
    let isShowSideBar=this.data.isShowSideBar
    isShowSideBar=!isShowSideBar;
    //console.log(isShowSideBar);
    this.setData({
      isShowSideBar
    })
  },
  //手风琴面板
  onChange(event) {
    //console.log(event.detail);
    this.setData({
      activeName: event.detail,
    });
  },
  //侧边导航栏
  onChange1(event) {
    console.log(event.detail);
    let index=event.detail;
    let rightContent=this.data.allData[index].deptType;
    this.setData({
      rightContent
    })
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {
    //页面加载时就取出数据,构造左侧导航栏
    let leftMenu=this.data.allData.map(v=>v.weekday);
    //右侧的内容
    let rightContent=this.data.allData[0].deptType
    //console.log(leftMenu);
    this.setData({
      leftMenu,
      rightContent
    })
  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {
      //页面显示的时候,设置回初始状态
    this.setData({
      isShowSideBar:false,
    })
  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {

  }
})